apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: open-object-s3minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: dynamic-bucket
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /data
          name: data
        command:
        - sh
        - "-c"
        - |
            while true; do
              echo "huizhi testing";
              echo "yes ">>/data/yes.txt;
              sleep 120s
            done;
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: csi-s3-pvc