apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: dynamic-bucket
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: nginx
        image: nginx
        command:
        - sh
        - "-c"
        - |
            while true; do
              echo "huizhi testing";
              echo "yes ">>/data/yes.txt;
              sleep 120s
            done;