kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}-csi-provisioner
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.name }}-csi-provisioner
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      component: {{ .Values.name }}-csi-provisioner
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        component: {{ .Values.name }}-csi-provisioner
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
        key: node-role.kubernetes.io/master
      priorityClassName: system-cluster-critical
      serviceAccount: {{ .Values.name }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: csi-provisioner
          image: {{ .Values.images.provisioner.image }}:{{ .Values.images.provisioner.tag }}
          args:
            - --csi-address=$(ADDRESS)
            - --volume-name-prefix=fuse
            - --extra-create-metadata=true
            - --timeout=10m
          env:
            - name: ADDRESS
              value: {{ .Values.global.kubelet_dir }}/plugins/{{ .Values.driver }}/csi.sock
            - name: TZ
              value: Asia/Shanghai
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: socket-dir
              mountPath: {{ .Values.global.kubelet_dir }}/plugins/{{ .Values.driver }}
      volumes:
        - name: socket-dir
          hostPath:
            path: {{ .Values.global.kubelet_dir }}/plugins/{{ .Values.driver }}
            type: DirectoryOrCreate
