apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
stringData:
  host: {{ .Values.minio.host }}
  accesskey: {{ .Values.minio.accesskey }}
  secretkey: {{ .Values.minio.secretkey }}
  region: {{ .Values.minio.region }}
