kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.name }}-s3minio
provisioner: {{ .Values.driver }}
parameters:
  driverName: s3minio
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.name }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Values.namespace }}
  csi.storage.k8s.io/node-publish-secret-name: {{ .Values.name }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ .Values.namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ .Values.name }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Values.namespace }}
allowVolumeExpansion: true