name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Docker amd64 meta
        id: meta-amd64
        uses: docker/metadata-action@v3
        with:
          images: thebeatles1994/open-object
          tags: |
            type=ref,event=tag
      - name: Docker arm64 meta
        id: meta-arm64
        uses: docker/metadata-action@v3
        with:
          images: thebeatles1994/open-object
          tags: |
            type=ref,event=tag,suffix=-arm64
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push amd64
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: ./build/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ${{ steps.meta-amd64.outputs.tags }}
      - name: Build and push arm64
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: ./build/Dockerfile.arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ${{ steps.meta-arm64.outputs.tags }}-arm64
